services:
  welyat.postgres:
    image: postgres:16-alpine
    container_name: welyat-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: welyat_v0_dev
      POSTGRES_USER: welyat
      POSTGRES_PASSWORD: welyat
    networks:
      - proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U welyat -d welyat_v0_dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  welyat.backend:
    build:
      context: ./backend-welyat
      dockerfile: Dockerfile.dev
    container_name: welyat-backend-dev
    restart: unless-stopped
    env_file:
      - ./backend-welyat/.env
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      DB_HOST: welyat.postgres
      DB_PORT: 5432
      DB_NAME: welyat_v0_dev
      DB_USER: welyat
      DB_PASSWORD: welyat
      FRONTEND_URL: https://welyat.codialis.com
    depends_on:
      welyat.postgres:
        condition: service_healthy
    networks:
      - proxy
    volumes:
      - ./backend-welyat:/app
      - backend_node_modules:/app/node_modules
    command: sh -c "chmod +x ./init.sh && ./init.sh && npm run dev"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.welyatapi.rule=Host(`welyatapi.codialis.com`)"
      - "traefik.http.routers.welyatapi.entrypoints=websecure"
      - "traefik.http.routers.welyatapi.tls.certresolver=myresolver"
      - "traefik.http.services.welyatapi.loadbalancer.server.port=3000"

  welyat.frontend:
    build:
      context: ./frontend-welyat
      dockerfile: Dockerfile.dev
    container_name: welyat-frontend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_APP_ID: sina-welyat
      VITE_API_URL: https://welyatapi.codialis.com/api/v1
    depends_on:
      - welyat.backend
    networks:
      - proxy
    volumes:
      - ./frontend-welyat:/app
      - frontend_node_modules:/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.welyat.rule=Host(`welyat.codialis.com`)"
      - "traefik.http.routers.welyat.entrypoints=websecure"
      - "traefik.http.routers.welyat.tls.certresolver=myresolver"
      - "traefik.http.services.welyat.loadbalancer.server.port=4000"

networks:
  proxy:
    external: true
volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
